/* THIS FILE IS AUTOGENERATED BY RUN `yarn cic`, YOU DON'T NEED EDIT IT */
import React from 'react'
import Cheveron from '~/icons/cheveron.svg'
import Location from '~/icons/location.svg'
import Time from '~/icons/time.svg'

export type IconName = 'cheveron' | 'location' | 'time'

const iconsDict: { [key in IconName]: React.FC } = {
  cheveron: Cheveron,
  location: Location,
  time: Time
}

interface IconProps extends React.SVGProps<SVGSVGElement> {
  name: IconName
}

export default function Icon({ name, ...props }: IconProps) {
  return React.createElement(iconsDict[name], props)
}
