/* THIS FILE IS AUTOGENERATED BY RUN `yarn cic`, YOU DON'T NEED EDIT IT */
import React from 'react'
import Location from 'icons/location.svg'
import Time from 'icons/time.svg'

export type IconName = 'location' | 'time'

const iconsDict: { [key in IconName]: React.FC } = {
  location: Location,
  time: Time
}

interface IconProps extends React.SVGProps<SVGSVGElement> {
  name: IconName
}

export default function Icon({ name, ...props }: IconProps) {
  return React.createElement(iconsDict[name], props)
}
